#
# Module manifest for module 'PrinterExorcism'
#
# Generated by: Michael Levesque
# Updated on: 6/5/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'PrinterExorcism.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = '07b30514-7143-4fbf-b54e-48f32b9bb96b'

    # Author of this module
    Author = 'Michael Levesque'

    # Company or vendor of this module
    CompanyName = ''

    # Copyright statement for this module
    Copyright = 'This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License.'

    # Description of the functionality provided by this module
    Description = 'Performs safe, two-phase printer cleanup for user or system-wide environments, including ghost and GPO-linked printers.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @('Exorcist\Common.ps1')

    # Functions to export from this module
    FunctionsToExport = @(
        'Start-PrinterExorcismSession',
        'Make-PrintersSuffer',
        'Start-SystemWidePrinterCleanup',
        'Show-PrinterDiscovery',
        'Invoke-PrinterDiscovery',
        'Invoke-PrinterExorcism'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('printers', 'cleanup', 'powershell', 'gpo', 'registry', 'automation')

            # A URL to the license for this module.
            LicenseUri = 'https://opensource.org/licenses/MIT'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/deeptree/printerexorcism'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = 'Initial release with two-phase cleanup, registry and WMI purging, ghost detection, and discovery mode.'

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = 'https://docs.deeptree.io/printerexorcism'

    # Default prefix for commands exported from this module.
    # DefaultCommandPrefix = ''

}
